### ISSUE TITLE
Parse TSV files

### ISSUE THREAD

**Issue by erdalkaraca** [bids-standard/pybids-refactor#14]
TSV files should be parsed by default. Complexity should be similar to or less than metadata JSON files (inheritance principle does not apply to TSV files).

What to clarify:
- Read only column names of TSV files or also the rows?
- What format to use for parsed TSV files? - numpy, pandas or simple records returned by CSVReader?

**Comment by effigies** [comment]
> Read only column names of TSV files or also the rows?

For `participants.tsv`, `sessions.tsv` and `scans.tsv`, I think it makes sense to read the whole things. They're not very large, and they include metadata that could help select files (e.g., `layout.get(suffix="bold", extension=".nii.gz", gender="F")`).

For events.tsv

> What format to use for parsed TSV files? - numpy, pandas or simple records returned by CSVReader?

We've generally used pandas, so PyBIDS will not get heavier. I guess it's mostly a question of whether we need the dataframe operations internally in ANCP-BIDS; if not then we could use numpy or CSV and make sure that users (or PyBIDS modules that need it) have a straightforward process for putting them in dataframes if they want to use pandas.

**Comment by erdalkaraca** [comment]
(all) TSV files are now loaded by default, see the following unit test as an example:

`tests.auto.test_basic.BasicTestCase.test_participants_tsv`

I have not done any performance regression tests, but if there are significant ones, we may switch to lazily load TSV file contents.
