### ISSUE TITLE
ignore & force_index

### ISSUE THREAD

**Issue by adelavega** [bids-standard/pybids-refactor#19]
`BIDSLayoutIndexer` has two options: `ignore` and `force_index`:

`ignore` 
- excludes patterns from the index tree. by default, it excludes 4 directories (`code`, `stimuli`, `models`, `sourcedata`) + all hidden files (`.`). 
- `code`, `stimuli` and `source` are identified as folders to be ignored in the bids-schema (although they are only identified as optional). 

We could implement this as a default `filter` on `.get` 

`force_index` has two functions:
- allows those folders excluded by default in `ignore` to be indexed. it's not really clear how often this would be useful
- allows patterns listed to be index, but not pass validation (even if validation=True).

@effigies and I think we could potentially deprecate `force_index`, but need to keep `ignore`

`**filters` argument to `BIDSLayoutIndexer` is supposed to set default arguments `.get` but its unclear if this is fully functional at the moment. This could be the vehicle for implementing `ignore`.

**Comment by adelavega** [comment]
@erdalkaraca any progress on implementing `ignore`? Currently many tests fail because `./models` is ignored by default in pybids, and files within it will fail validation

**Comment by erdalkaraca** [comment]
so, if we ignore resource (files and folders in the dataset) from the index tree, they will not be available for queries... is that fine?

there is an request in ancpbids to implement a .bidsignore file:
https://github.com/ANCPLabOldenburg/ancp-bids/issues/44

if the parameter ignoe=True, ancpbids could conisder the .bidsignore file to not add files/folders to the index tree

**Comment by adelavega** [comment]
yes, that is how it was intended to be used for two reasons:

1) to skip validation on known invalid files that are not meant to be indexed
2) to skip indexing selectively because pybids was slow (especially hidden files could be a lot) - less relevant now

**Comment by adelavega** [comment]
btw, this got me thinking that ignoring `./models` by default was not very principled (other folders such as `stimuli/` are, because they are mentioned in bids schema). so in the future we should probably only ignore by default folders that are mention to be ignored in the bids schema. 

`stimuli/` is another good example of a folder to be ignored, because its a designated folder in bids, but there is no designated file name structure for the contained files.

**Comment by erdalkaraca** [comment]
added support for .bidsignore:
- filters are fnmatch patterns
- ignore is True by default, so if a .bidsignore file is present in the root folder it will be processed

@adelavega let me know if this is sufficient... at least a .bidsignore would have to be added to the existing unit test datasets which is a breaking change but from my point of view is a clean solution

**Comment by adelavega** [comment]
Thank you. I think this is a good solution.

However, I think it will break a lot of people's workflows if we suddenly start indexing folders which were previously ignored. Basically we need a "default" .bidsignore file that is applied.

I can understand if you don't want to put this into ancpbids, but for the sake of providing (at least temporary) backwards compatibility in pybids, could you support passing a list of folders to be ignored at run-time?

cc: @effigies what do you think?

**Comment by erdalkaraca** [comment]
OK, you can also add a list of fnmatch patterns dynamically by providing a list to ignore instead of True/False, see unit test:

tests.auto.test_ignored_resources.IgnoredResourcesTestCase.test_ignore_file_dynamic

```
    def test_ignore_file_dynamic(self):
        ds = load_dataset(DS005_DIR_IGNORED_RESOURCES, ignore=["models", "stimuli", ".*"])
        assert ds.get_folder("models") is None
        assert ds.get_folder("stimuli") is None
        assert ds.get_file(".dummy") is None
        assert ds.query(sub="01", suffix="bold") is not None
        assert ds.dataset_description is not None

        assert ds.get_file(".bidsignore") is None
```

**Comment by adelavega** [comment]
Cool. I think this should work. The only "issue" is that technically this is breaking because previously it would apply these rules + whatever was in `.bidsignore`, but that doesn't make much sense.

I think I will apply a deprecation cycle such that if no `.bidsignore` file is found, it applies these default rules, but issues a `DeprecationWarning` encouraging users to add a `.bidsignore` file.

**Comment by effigies** [comment]
I don't think we ever respected .bidsignore. It is not a BIDS concept and its interpretation in pybids would be ambiguous (does it mean do not index or do not validate?).

**Comment by erdalkaraca** [comment]
> I don't think we ever respected .bidsignore. It is not a BIDS concept and its interpretation in pybids would be ambiguous (does it mean do not index or do not validate?).

if something is not indexed, it cannot be validated, at least using the ancpbids validator as it only operates on the index tree (in-memory graph of dataset)

**Comment by adelavega** [comment]
> I don't think we ever respected .bidsignore. It is not a BIDS concept and its interpretation in pybids would be ambiguous (does it mean do not index or do not validate?).

It would mean both, which is what `ignore` currently does. I think ignoring a set of folders by default is probably more unprincipled, so I prefer this. If we wanted to be strict, we can ignore `.bidsignore` and pass `[]` to ancpids, but I like this suggestion

`force_index` for now is unimplemented, which would mean "index without validating"
