### ISSUE TITLE
layout.regex_search as default for queries

### ISSUE THREAD

**Issue by adelavega** [bids-standard/pybids-refactor#2]

**Comment by erdalkaraca** [comment]
There is already BIDSLayout.get(regex_search=True) which will assume all (applicable) filter patterns to be regex expressions. Do you really mean a separate function like BIDSLayout.regex_search(...)?

**Comment by adelavega** [comment]
To clarify, it looks like currently pybids has `regex_search` as an initialization argument to `BIDSLayout`:

```
    regex_search : bool
        Whether to require exact matching (True) or regex
        search (False, default) when comparing the query string to each
        entity in .get() calls. This sets a default for the instance, but
        can be overridden in individual .get() requests.
```

This functionality seems to be used in one place in `bids.variables`: `_load_tsv_variables`:

https://github.com/bids-standard/pybids/blob/b3351dd25fa74801fa7033ce7e4046382520c461/bids/variables/io.py#L413

**Comment by effigies** [comment]
It is used outside pybids, and is valid in all `get()`. We just need a state variable to set the default value for `layout.get()` and we can deprecate it immediately. IMO, it should always be explicit.
