### ISSUE TITLE
Does ancpbids support regex queries?

### ISSUE THREAD

**Issue by adelavega** [bids-standard/pybids-refactor#36]

**Comment by erdalkaraca** [comment]
if you call ancpbids.query.query(regex_search=True), then all patterns will be interpreted as regex... default is regex_search=False, so, fnmatch will be used

**Comment by erdalkaraca** [comment]
@adelavega the current implementation of BIDSLayout already accounts for that switch to use regex

**Comment by adelavega** [comment]
Yes, of course! I'll close this
