### ISSUE TITLE
BIDSLayout.get_collections

### ISSUE THREAD

**Issue by adelavega** [bids-standard/pybids-refactor#6]

**Comment by erdalkaraca** [comment]
prereqs:
- parse tsv files by default: only column names or also rows?
- collect all distinct tsv file column names

**Comment by erdalkaraca** [comment]
Depends on #14

**Comment by adelavega** [comment]
The plan for this was to use the previous implementation, with any necessary changes so that it would work with any API changes in ancpbids `BIDSLayout.get`. I'm happy to consider more substantial refactoring of this function that would improve its performance, however.

**Comment by adelavega** [comment]
Closed with #21
