### ISSUE TITLE
participants.tsv is not indexed

### ISSUE THREAD

**Issue by adelavega** [bids-standard/pybids-refactor#7]

**Comment by erdalkaraca** [comment]
This has to be generically implemented the same way JSON metadata files are handled:
ancpbids.plugins.plugin_dsloader.DatasetPopulationPlugin._type_handler_MetadataFile

There is already a function to read tsv files:
ancpbids.plugins.plugin_files_handlers.read_tsv

It supports numpy, pandas and simple DictReader records.

**Comment by adelavega** [comment]
well I don't mean we have to read the file, but it is not findable via querying, unless I'm mistaken

**Comment by effigies** [comment]
Participants.tsv in the schema: https://github.com/bids-standard/bids-specification/blob/v1.8.0/src/schema/rules/files/common/tables.yaml#L2-L7

**Comment by adelavega** [comment]
@erdalkaraca do you know why `participants.tsv` fails validation and how to fix it?

```
E               bids.exceptions.BIDSValidationError: Missing required node suffix at participants.tsv.
E               Missing required node entities at participants.tsv.
E               Missing required node suffix at participants.tsv.
E               Missing required node entities at participants.tsv.
```

**Comment by erdalkaraca** [comment]
this is a false positive as participants.tsv is modeled as a TSVFile which derives from Artifact and all Artifact instances must have their name comply with the BIDS naming scheme... I have to figure out how to best handle participants.tsv and normal TSV files

**Comment by adelavega** [comment]
Okay, I was just a bit confused bc the older ancpbids.BIDSLayout doesn't fail validation on this file, but that makes sense. 

In the meantime I'll turn `validate=False` when loading all pybids test datasets.

**Comment by erdalkaraca** [comment]
@adelavega should be working again
